/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import cordinator.Cordinator;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author HP
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabelDobrodosao = new javax.swing.JLabel();
        jLabelVreme = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelImePrezime = new javax.swing.JLabel();
        jLabelDatumRodjenja = new javax.swing.JLabel();
        jLabelKorisnickoIme = new javax.swing.JLabel();
        jButtonIzmenaPoslasticar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUnosKupca = new javax.swing.JMenuItem();
        jMenuItemPrikazKupaca = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUnosKolaca = new javax.swing.JMenuItem();
        jMenuItemPrikazKolaca = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemUnosSmene = new javax.swing.JMenuItem();
        jMenuItemPrikazSmena = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemUnosRacuna = new javax.swing.JMenuItem();
        jMenuItemPrikazRacuna = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDobrodosao.setText("Dobrodosli, ");

        jLabelVreme.setText("Vreme");

        jLabelDatum.setText("Datum");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trenutno prijavljeni poslastičar"));

        jLabel1.setText("Ime i prezime:");

        jLabel3.setText("Datum rodjenja:");

        jLabel4.setText("Korisnicko ime:");

        jLabelImePrezime.setText("jLabel2");

        jLabelDatumRodjenja.setText("jLabel2");

        jLabelKorisnickoIme.setText("jLabel2");

        jButtonIzmenaPoslasticar.setText("Izmena ličnih podataka");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKorisnickoIme)
                            .addComponent(jLabelImePrezime))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDatumRodjenja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIzmenaPoslasticar)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelImePrezime))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDatumRodjenja)
                    .addComponent(jButtonIzmenaPoslasticar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelKorisnickoIme))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenu1.setText("Kupac");

        jMenuItemUnosKupca.setText("Unos kupca");
        jMenuItemUnosKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosKupcaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosKupca);

        jMenuItemPrikazKupaca.setText("Prikaz svih kupaca");
        jMenuItemPrikazKupaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazKupacaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPrikazKupaca);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kolač");

        jMenuItemUnosKolaca.setText("Unos kolača");
        jMenuItemUnosKolaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosKolacaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnosKolaca);

        jMenuItemPrikazKolaca.setText("Prikaz svih kolača");
        jMenuItemPrikazKolaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazKolacaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPrikazKolaca);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Smena");

        jMenuItemUnosSmene.setText("Unos smene");
        jMenuItemUnosSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosSmeneActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemUnosSmene);

        jMenuItemPrikazSmena.setText("Prikaz svih smena");
        jMenuItemPrikazSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazSmenaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPrikazSmena);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Račun");

        jMenuItemUnosRacuna.setText("Unos novog racuna");
        jMenuItemUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosRacunaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemUnosRacuna);

        jMenuItemPrikazRacuna.setText("Prikaz svih racuna");
        jMenuItemPrikazRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazRacunaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPrikazRacuna);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDobrodosao)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(657, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatum)
                            .addComponent(jLabelVreme))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelDobrodosao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDatum)
                .addGap(12, 12, 12)
                .addComponent(jLabelVreme)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosKupcaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajKupcaFormu();
    }//GEN-LAST:event_jMenuItemUnosKupcaActionPerformed

    private void jMenuItemUnosKolacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosKolacaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajKolacFormu();
    }//GEN-LAST:event_jMenuItemUnosKolacaActionPerformed

    private void jMenuItemPrikazKolacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazKolacaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazKolacaFormu();
    }//GEN-LAST:event_jMenuItemPrikazKolacaActionPerformed

    private void jMenuItemUnosSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosSmeneActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajSmenaFormu();
    }//GEN-LAST:event_jMenuItemUnosSmeneActionPerformed

    private void jMenuItemPrikazKupacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazKupacaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazKupacaFormu();
    }//GEN-LAST:event_jMenuItemPrikazKupacaActionPerformed

    private void jMenuItemUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosRacunaActionPerformed
        try {
            // TODO add your handling code here:
            Cordinator.getInstance().otvoriDodajracunFormu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUnosRacunaActionPerformed

    private void jMenuItemPrikazSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazSmenaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikaziSmeneFormu();
    }//GEN-LAST:event_jMenuItemPrikazSmenaActionPerformed

    private void jMenuItemPrikazRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazRacunaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazRacunaFormu();
    }//GEN-LAST:event_jMenuItemPrikazRacunaActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmenaPoslasticar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelDatumRodjenja;
    private javax.swing.JLabel jLabelDobrodosao;
    private javax.swing.JLabel jLabelImePrezime;
    private javax.swing.JLabel jLabelKorisnickoIme;
    private javax.swing.JLabel jLabelVreme;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemPrikazKolaca;
    private javax.swing.JMenuItem jMenuItemPrikazKupaca;
    private javax.swing.JMenuItem jMenuItemPrikazRacuna;
    private javax.swing.JMenuItem jMenuItemPrikazSmena;
    private javax.swing.JMenuItem jMenuItemUnosKolaca;
    private javax.swing.JMenuItem jMenuItemUnosKupca;
    private javax.swing.JMenuItem jMenuItemUnosRacuna;
    private javax.swing.JMenuItem jMenuItemUnosSmene;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelDobrodosao() {
        return jLabelDobrodosao;
    }

    public void setjLabelDobrodosao(JLabel jLabelDobrodosao) {
        this.jLabelDobrodosao = jLabelDobrodosao;
    }

    public JLabel getjLabelDatum() {
        return jLabelDatum;
    }

    public JLabel getjLabelVreme() {
        return jLabelVreme;
    }

    public JLabel getjLabelDatumRodjenja() {
        return jLabelDatumRodjenja;
    }

    public JLabel getjLabelImePrezime() {
        return jLabelImePrezime;
    }

    public JLabel getjLabelKorisnickoIme() {
        return jLabelKorisnickoIme;
    }

    public JButton getjButtonIzmenaPoslasticar() {
        return jButtonIzmenaPoslasticar;
    }

    public void addBtnIzmeniProfilActionListener(ActionListener actionListener) {
        jButtonIzmenaPoslasticar.addActionListener(actionListener);
    }
    
    
}
